### ISSUE TITLE
fireIndexKBDI function don't find any coincidence of the drought factor in the table

### ISSUE THREAD

**Issue by acunill** [EcoFire/firebehavioR#2]
Hello,

I am trying to calculate the collection of fire weather indices based on cumulative weather observations implemented in the fireIndexKBDI function.

The problem is that sometimes the piece of code that gets the drought factor (DF) fails to match a value and the for loop crashes. This is an example:

```
# Input values from my serial calculation
temp <- 25.41922
kbdi <- 49.86867
map <- 589.3577

# Code for reply the fail
kbdiTable <- kbdiTable
droughtFactor <- rep(0, length(temp))
i <- 1 

# Code that fails
droughtFactor[i] <- kbdiTable$DF[temp[i] >= kbdiTable$MinTemp & 
                                  temp[i] < kbdiTable$MaxTemp & kbdi[i] >= kbdiTable$MinDI & 
                                  kbdi[i] <= kbdiTable$MaxDI & map >= kbdiTable$MinMAP & 
                                  map <= kbdiTable$MaxMAP]
```

Any idea how can I solve it?

Thanks

**Comment by EcoFire** [comment]
There is a gap between integers in kbdiTable. In this example, a value for 49.86867 falls between 49 and 50 so R returns a list with 0 rows.
This will be marked as an item to fix in a future version. For now this issue can be avoided by rounding the numeric inputs to 0 decimal places.

**Comment by acunill** [comment]
Thank you very much. It seemed easy to see where the fault was. All the best.
